USE test;

DROP TABLE IF EXISTS book;

CREATE TABLE book (
  id INT(10) NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL,
  author VARCHAR(100) NOT NULL,
  isbn VARCHAR(20) NOT NULL,
  printYear INT(4) NOT NULL,
  readAlready BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id))

  ENGINE = InnoDB DEFAULT CHARSET = utf8;